### ISSUE TITLE
homestead-prov repeatedly crashing

### ISSUE THREAD

**Issue by sebrexmetaswitch** [Metaswitch/crest#325]
#### Symptoms
hometead-prov crashes with the trace in homestead-prov-err.log:

> Unhandled Error
> Traceback (most recent call last):
>   File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/python/log.py", line 103, in callWithLogger
>     return callWithContext({"system": lp}, func, *args, **kw)
>   File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/python/log.py", line 86, in callWithContext
>     return context.call({ILogContext: newCtx}, func, *args, **kw)
>   File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/python/context.py", line 122, in callWithContext
>     return self.currentContext().callWithContext(ctx, func, *args, **kw)
>   File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/python/context.py", line 85, in callWithContext
>     return func(*args,**kw)
> --- <exception caught here> ---
>   File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
>     why = selectable.doRead()
>   File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 208, in doRead
>     return self._dataReceived(data)
>   File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 214, in _dataReceived
>     rval = self.protocol.dataReceived(data)
>   File "/usr/share/clearwater/crest/env/local/lib/python2.7/site-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/protocols/basic.py", line 765, in dataReceived
>     self.stringReceived(packet)
>   File "build/bdist.linux-x86_64/egg/thrift/transport/TTwisted.py", line 109, in stringReceived
> 
>   File "build/bdist.linux-x86_64/egg/telephus/cassandra/Cassandra.py", line 570, in recv_set_keyspace
> 
>   File "build/bdist.linux-x86_64/egg/telephus/cassandra/Cassandra.py", line 3860, in read
> 
> exceptions.AttributeError: 'TMemoryBuffer' object has no attribute 'trans'
> 

#### Impact
homestead-prov doesn't work

#### Release and environment 
latest dev code, on the staging system

#### Steps to reproduce
Try to run the live tests, or create a user from the Ellis web UI

**Comment by graemerobertson** [comment]
I haven't looked at this issue at all, but I suspect it was caused by https://github.com/Metaswitch/crest/pull/323 - I'm pretty sure this crash coincided with that PR getting merged (although it's possible that the merge triggered a rebuild which exposed a different problem or something...)

**Comment by sebrexmetaswitch** [comment]
That's why I looked at it, but I tried rebuilding from the release-114 tag in crest, and hit the same issue. So as far as I can tell the rebuild has exposed a different problem.
My best guess is that maybe a dependency has changed? I know for a fact that the last working crest build used a different version of Twisted:

in build 215 we see:
> Processing Twisted-16.7.0rc1.tar.bz2

but in build 216 (after which the live tests failed) we see:
> Best match: Twisted 16.7.0rc2

I don't know whether this is a red herring, but it does show that not all of our dependencies are pinned

**Comment by graemerobertson** [comment]
Nice, I'd say that is almost certainly causing the problem.

**Comment by GAB-MS** [comment]
We've hit this issue on one of our staging systems, causing Homer to repeatedly crash and restart with the same trace as in the topmost post. Any chance that we can get this sorted or backed out soon?

**Comment by johadalin** [comment]
@GAB-MS Investigating as we speak. Hoping to fix today

**Comment by johadalin** [comment]
@GAB-MS The above fix should do it. If you can update your systems to the latest code (checking that the install brings in thrft 0.9.3), and let us know if you're still hitting issues. 
Closing this down now, as the change fixes the issue on a number of my deployments
